spring.application.name=Quiz_Java
spring.datasource.url=jdbc:postgresql://ep-orange-water-ai8m24pc-pooler.c-4.us-east-1.aws.neon.tech/neondb?sslmode=require&channelBinding=require

# Credenciales separadas (Evita errores de sintaxis y filtrado de Maven)
spring.datasource.username=neondb_owner
spring.datasource.password=npg_Ey2MFoz1JAOl

# Driver y Dialecto específico para la comunicación con PostgreSQL
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# ===================================================================
# CONFIGURACIÓN DE HIBERNATE Y JPA
# ===================================================================

# 'update' creará automáticamente las tablas en la nube de Neon al arrancar
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true